"""create audit_log table

Revision ID: 3fef90fc3fef
Revises: 4e0346d3bbfc
Create Date: 2025-07-26 11:58:23.458554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fef90fc3fef'
down_revision: Union[str, Sequence[str], None] = '4e0346d3bbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holiday_calendars_id'), table_name='holiday_calendars')
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('audit_logs', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'updated_by_user_id')
    op.drop_column('audit_logs', 'created_by_user_id')
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'created_at')
    op.create_table('employee_holidays',
    sa.Column('holiday_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_holidays_employee_id_fkey')),
    sa.ForeignKeyConstraint(['holiday_id'], ['holiday_calendars.id'], name=op.f('employee_holidays_holiday_id_fkey'))
    )
    op.create_table('holiday_calendars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_optional', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_national', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('holiday_calendars_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('holiday_calendars_department_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('holiday_calendars_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('holiday_calendars_pkey'))
    )
    op.create_index(op.f('ix_holiday_calendars_id'), 'holiday_calendars', ['id'], unique=False)
    # ### end Alembic commands ###
