"""create employee_addresses table

Revision ID: 638f73dc4058
Revises: 84f04f0acc3e
Create Date: 2025-07-21 16:36:25.052107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638f73dc4058'
down_revision: Union[str, Sequence[str], None] = '84f04f0acc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('passport_expiry', sa.Date(), nullable=True))
    op.add_column('employee_profiles', sa.Column('personal_email', sa.String(length=100), nullable=True))
    op.add_column('employee_profiles', sa.Column('highest_education', sa.String(length=100), nullable=True))
    op.add_column('employee_profiles', sa.Column('institution', sa.String(length=100), nullable=True))
    op.add_column('employee_profiles', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('employee_profiles', sa.Column('professional_certifications', sa.Text(), nullable=True))
    op.add_column('employee_profiles', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('employee_profiles', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('employee_profiles', sa.Column('bank_branch', sa.String(length=100), nullable=True))
    op.add_column('employee_profiles', sa.Column('swift_code', sa.String(length=50), nullable=True))
    op.add_column('employee_profiles', sa.Column('medical_conditions', sa.Text(), nullable=True))
    op.add_column('employee_profiles', sa.Column('dietary_restrictions', sa.Text(), nullable=True))
    op.add_column('employee_profiles', sa.Column('languages', sa.Text(), nullable=True))
    op.add_column('employee_profiles', sa.Column('hobbies', sa.Text(), nullable=True))
    op.add_column('employee_profiles', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('employee_profiles', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('employee_profiles', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('employee_profiles', sa.Column('updated_at', sa.Date(), nullable=True))
    op.alter_column('employee_profiles', 'skills',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('employee_profiles_tax_id_key'), 'employee_profiles', type_='unique')
    op.drop_column('employee_profiles', 'education_level')
    op.drop_column('employee_profiles', 'tax_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employee_profiles', sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('employee_profiles_tax_id_key'), 'employee_profiles', ['tax_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employee_profiles', 'skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('employee_profiles', 'updated_at')
    op.drop_column('employee_profiles', 'created_at')
    op.drop_column('employee_profiles', 'updated_by_user_id')
    op.drop_column('employee_profiles', 'created_by_user_id')
    op.drop_column('employee_profiles', 'hobbies')
    op.drop_column('employee_profiles', 'languages')
    op.drop_column('employee_profiles', 'dietary_restrictions')
    op.drop_column('employee_profiles', 'medical_conditions')
    op.drop_column('employee_profiles', 'swift_code')
    op.drop_column('employee_profiles', 'bank_branch')
    op.drop_column('employee_profiles', 'bank_account_number')
    op.drop_column('employee_profiles', 'bank_name')
    op.drop_column('employee_profiles', 'professional_certifications')
    op.drop_column('employee_profiles', 'graduation_year')
    op.drop_column('employee_profiles', 'institution')
    op.drop_column('employee_profiles', 'highest_education')
    op.drop_column('employee_profiles', 'personal_email')
    op.drop_column('employee_profiles', 'passport_expiry')
    # ### end Alembic commands ###
