"""Add created_at and updated_at defaults

Revision ID: 833cb9aa3613
Revises: 7a9af5f25015
Create Date: 2025-07-22 11:44:08.112893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833cb9aa3613'
down_revision: Union[str, Sequence[str], None] = '7a9af5f25015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_profiles', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('employee_profiles', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('employee_profiles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
