"""Add category and is_active to skills

Revision ID: a75baa62e6a1
Revises: 2f7066d671e4
Create Date: 2025-08-02 12:39:00.286937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75baa62e6a1'
down_revision: Union[str, Sequence[str], None] = '2f7066d671e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('category', sa.Enum('TECHNICAL', 'SOFT_SKILL', 'LANGUAGE', 'CERTIFICATION', 'TOOL', 'FRAMEWORK', name='skill_category_enum'), nullable=True))
    op.add_column('skills', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'is_active')
    op.drop_column('skills', 'category')
    # ### end Alembic commands ###
